#!/bin/bash
# Hacky script to compile to flash.so
source /usr/lib/tkConfig.sh
cd $(dirname $0)
gcc -Wl,-soname,flash.so -Wl,--no-as-needed -lX11 $TK_LIB_FLAG -I/usr/include/tcl $TK_INCLUDE_SPEC -O2 -fPIC -shared flash.c -o flash.so
